AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  inchcape-api

  Sample SAM Template for inchcape-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: True
Resources:
  InchcapeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      PackageType: Image
      Environment:
        Variables:
          URL_TYPICODE: "https://jsonplaceholder.typicode.com/posts"
      Architectures:
        - x86_64
      Events:
        Inchcape:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /typicode
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InchcapeApi:
    Description: "API Gateway endpoint URL for Prod stage for Inchcape function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/typicode/"
  InchcapeFunction:
    Description: "Inchcape Lambda Function ARN"
    Value: !GetAtt InchcapeFunction.Arn
  InchcapeFunctionIamRole:
    Description: "Implicit IAM Role created for Inchcape function"
    Value: !GetAtt InchcapeFunctionRole.Arn
